### ISSUE TITLE
I am trying to make PINCE package on NixOS

### ISSUE THREAD

**Issue by TheK0tYaRa** [korcankaraokcu/PINCE#104]
The problems i am facing is that there is not a single image on the buttons and running with sudo fails. The sudo part i will figure out myself. Also it fails to work with GDB and writes that the GDB is not initialized. I may be missing some packages. Please help me make this package reach more users.

**Comment by TheK0tYaRa** [comment]
The current issue is
```
>   File "/build/PINCE/libPINCE/GDB_Engine.py", line 202, in send_command
>     raise type_defs.GDBInitializeException
> libPINCE.type_defs.GDBInitializeException: GDB not initialized
```

**Comment by TheK0tYaRa** [comment]
On further inspection, this is the expanded error log
```
running build_ext
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
/build/PINCE/libPINCE/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
ScriptUtils (unittest.loader._FailedTest) ... ERROR
GDBCommandExtensions (unittest.loader._FailedTest) ... ERROR
test_split_symbol (tests.SysUtils_tests.SysUtils_tests) ... ok
test_read_registers (tests.GDB_Engine_tests.GDB_Engine_tests) ... ERROR
test_change_text_length (tests.GuiUtils_tests.GuiUtils_tests) ... ok

======================================================================
ERROR: ScriptUtils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: ScriptUtils
Traceback (most recent call last):
  File "/nix/store/i1m8r7mv8h47wr850cdsxksy22lv6gsz-python3-3.9.6/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/PINCE/libPINCE/gdb_python_scripts/ScriptUtils.py", line 18, in <module>
    import gdb, sys, traceback, functools
ModuleNotFoundError: No module named 'gdb'


======================================================================
ERROR: GDBCommandExtensions (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: GDBCommandExtensions
Traceback (most recent call last):
  File "/nix/store/i1m8r7mv8h47wr850cdsxksy22lv6gsz-python3-3.9.6/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/PINCE/libPINCE/gdb_python_scripts/GDBCommandExtensions.py", line 18, in <module>
    import gdb, pickle, json, sys, re, struct, io, ctypes, os, shelve, distorm3
ModuleNotFoundError: No module named 'gdb'


======================================================================
ERROR: test_read_registers (tests.GDB_Engine_tests.GDB_Engine_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/PINCE/tests/GDB_Engine_tests.py", line 23, in test_read_registers
    register_dict = GDB_Engine.read_registers()
  File "/build/PINCE/libPINCE/GDB_Engine.py", line 1185, in read_registers
    return send_command("pince-read-registers", recv_with_file=True)
  File "/build/PINCE/libPINCE/GDB_Engine.py", line 202, in send_command
    raise type_defs.GDBInitializeException
libPINCE.type_defs.GDBInitializeException: GDB not initialized

----------------------------------------------------------------------
Ran 5 tests in 0.001s
```

**Comment by korcankaraokcu** [comment]
if you are using the newest PINCE build, it uses system gdb. Check if your system gdb resides in `/bin/gdb`

**Comment by TheK0tYaRa** [comment]
Does it get the executable location from the environment or does it execute it directly? Wait, why am i even asking, i can search for that.

**Comment by korcankaraokcu** [comment]
It's hardcoded as `/bin/gdb` because all of the supported systems use that path. Maybe the `whereis` utility could be used if the path should be set dynamically.

**Comment by brkzlr** [comment]
Closing as we don't officially support NixOS neither plan to for local dev installs. We have AppImages now.

https://github.com/korcankaraokcu/PINCE/pull/250 This PR contains work that makes it possible to have a local dev install on NixOS if you wish so.

https://github.com/korcankaraokcu/PINCE/pull/250#issuecomment-2069403596 There are also some instructions here on how to make AppImages run.
