### ISSUE TITLE
Attaching to process fails

### ISSUE THREAD

**Issue by zephryn** [korcankaraokcu/PINCE#128]
Selecting an existing process in the GUI causes it to halt the process, but only manage to output the below info before showing "No Process Selected [stopped]" at the top of the main window. The process remains halted until I select another one to attach to or exit the program, however.

For reference: install location is `/home/zephryn/download/git/PINCE`, attempting to attach to `wineserver`.

```
Exception in thread Thread-6 (state_observe_thread):
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 304, in state_observe_thread
    child.expect_exact("\r\n")  # A new line for TTY devices
  File "/usr/lib/python3.10/site-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python3.10/site-packages/pexpect/expect.py", line 169, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3.10/site-packages/pexpect/pty_spawn.py", line 501, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3.10/site-packages/pexpect/spawnbase.py", line 169, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 9] Bad file descriptor
Detached from the process with PID:9055
Last command: set logging off
^done
0.0006880760192871094
Last command: set logging file /dev/shm/PINCE-connection/-1/gdb_log.txt
=cmd-param-changed,param="logging file",value="/dev/shm/PINCE-connection/-1/gdb_log.txt"
^done0.0003829002380371094
Last command: source /home/zephryn/.config/PINCE/PINCE_USER_FILES/gdbinit

^done
0.0008783340454101562
Last command: attach 25105
=thread-group-started,id="i1",pid="25105"
=thread-created,id="1",group-id="i1"
=library-loaded,id="/usr/lib64/libc.so.6",target-name="/usr/lib64/libc.so.6",host-name="/usr/lib64/libc.so.6",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f5fc6093700",to="0x00007f5fc621679d"}]
=library-loaded,id="/lib64/ld-linux-x86-64.so.2",target-name="/lib64/ld-linux-x86-64.so.2",host-name="/lib64/ld-linux-x86-64.so.2",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f5fc628c090",to="0x00007f5fc62b3ba5"}]
~"[Thread debugging using libthread_db enabled]\n"
~"Using host libthread_db library \"/lib64/libthread_db.so.1\".\n"
~"0x00007f5fc618505a in epoll_wait () from /usr/lib64/libc.so.6\n"
*stopped,frame={addr="0x00007f5fc618505a",func="epoll_wait",args=[],from="/usr/lib64/libc.so.6",arch="i386:x86-64"},thread-id="1",stopped-threads="all",core="3"
^done
0.03021693229675293
Last command: set $GDBINIT_AA_PATH="/home/zephryn/.config/PINCE/PINCE_USER_FILES/gdbinit_after_attach"
^done
0.0005424022674560547
Last command: set $PINCE_PATH="/home/zephryn/download/git/PINCE"
^done
0.0008096694946289062
Last command: source gdb_python_scripts/GDBCommandExtensions.py
&"Traceback (most recent call last):\n"
&"  File \"gdb_python_scripts/GDBCommandExtensions.py\", line 18, in <module>\n"
&"    import gdb, pickle, json, sys, re, struct, ctypes, os, shelve, distorm3\n"
&"ModuleNotFoundError: No module named 'distorm3'\n"
^done
0.012291908264160156
Last command: pince-parse-and-eval
&"/dev/shm/PINCE-connection/25105/gdb_command.txt:1: Error in sourced command file:\n"
&"Undefined command: \"pince-parse-and-eval\".  Try \"help\".\n"
^error,msg="/dev/shm/PINCE-connection/25105/gdb_command.txt:1: Error in sourced command file:\nUndefined command: \"pince-parse-and-eval\".  Try \"help\"."
Traceback (most recent call last):
  File "/home/zephryn/download/git/PINCE/PINCE.py", line 1474, in pushButton_Open_clicked
    if self.parent().attach_to_pid(pid):
  File "/home/zephryn/download/git/PINCE/PINCE.py", line 1136, in attach_to_pid
    attach_result = GDB_Engine.attach(pid, gdb_path)
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 607, in attach
    inferior_arch = get_inferior_arch()
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 1154, in get_inferior_arch
    if parse_and_eval("$rax") == "void":
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 1023, in parse_and_eval
    return send_command("pince-parse-and-eval", send_with_file=True, file_contents_send=(expression, cast),
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 238, in send_command
    output = pickle.load(open(recv_file, "rb"))
EOFError: Ran out of input
Last command: info threads
~"  Id   Target Id                                      Frame \n"
~"* 1    Thread 0x7f5fc6053000 (LWP 25105) \"wineserver\" 0x00007f5fc618505a in epoll_wait () from /usr/lib64/libc.so.6\n"
^done
0.0004863739013671875
Last command: disas /r $pc,+200
~"Dump of assembler code from 0x7f5fc618505a to 0x7f5fc6185122:\n"
~"=> 0x00007f5fc618505a <epoll_wait+28>:\t48 3d 00 f0 ff ff\tcmp    $0xfffffffffffff000,%rax\n"
~"   0x00007f5fc6185060 <epoll_wait+34>:\t77 5e\tja     0x7f5fc61850c0 <epoll_wait+130>\n"
~"   0x00007f5fc6185062 <epoll_wait+36>:\tc3\tret    \n"
~"   0x00007f5fc6185063 <epoll_wait+37>:\t0f 1f 44 00 00\tnopl   0x0(%rax,%rax,1)\n"
~"   0x00007f5fc6185068 <epoll_wait+42>:\t48 83 ec 28\tsub    $0x28,%rsp\n"
~"   0x00007f5fc618506c <epoll_wait+46>:\t89 54 24 18\tmov    %edx,0x18(%rsp)\n"
~"   0x00007f5fc6185070 <epoll_wait+50>:\t48 89 74 24 10\tmov    %rsi,0x10(%rsp)\n"
~"   0x00007f5fc6185075 <epoll_wait+55>:\t89 7c 24 0c\tmov    %edi,0xc(%rsp)\n"
~"   0x00007f5fc6185079 <epoll_wait+59>:\t89 4c 24 1c\tmov    %ecx,0x1c(%rsp)\n"
~"   0x00007f5fc618507d <epoll_wait+63>:\te8 bc 24 f7 ff\tcall   0x7f5fc60f753e <__pthread_enable_asynccancel>\n"
~"   0x00007f5fc6185082 <epoll_wait+68>:\t44 8b 54 24 1c\tmov    0x1c(%rsp),%r10d\n"
~"   0x00007f5fc6185087 <epoll_wait+73>:\t8b 54 24 18\tmov    0x18(%rsp),%edx\n"
~"   0x00007f5fc618508b <epoll_wait+77>:\t41 89 c0\tmov    %eax,%r8d\n"
~"   0x00007f5fc618508e <epoll_wait+80>:\t48 8b 74 24 10\tmov    0x10(%rsp),%rsi\n"
~"   0x00007f5fc6185093 <epoll_wait+85>:\t8b 7c 24 0c\tmov    0xc(%rsp),%edi\n"
~"   0x00007f5fc6185097 <epoll_wait+89>:\tb8 e8 00 00 00\tmov    $0xe8,%eax\n"
~"   0x00007f5fc618509c <epoll_wait+94>:\t0f 05\tsyscall \n"
~"   0x00007f5fc618509e <epoll_wait+96>:\t48 3d 00 f0 ff ff\tcmp    $0xfffffffffffff000,%rax\n"
~"   0x00007f5fc61850a4 <epoll_wait+102>:\t77 32\tja     0x7f5fc61850d8 <epoll_wait+154>\n"
~"   0x00007f5fc61850a6 <epoll_wait+104>:\t44 89 c7\tmov    %r8d,%edi\n"
~"   0x00007f5fc61850a9 <epoll_wait+107>:\t89 44 24 0c\tmov    %eax,0xc(%rsp)\n"
~"   0x00007f5fc61850ad <epoll_wait+111>:\te8 1c 25 f7 ff\tcall   0x7f5fc60f75ce <__pthread_disable_asynccancel>\n"
~"   0x00007f5fc61850b2 <epoll_wait+116>:\t8b 44 24 0c\tmov    0xc(%rsp),%eax\n"
~"   0x00007f5fc61850b6 <epoll_wait+120>:\t48 83 c4 28\tadd    $0x28,%rsp\n"
~"   0x00007f5fc61850ba <epoll_wait+124>:\tc3\tret    \n"
~"   0x00007f5fc61850bb <epoll_wait+125>:\t0f 1f 44 00 00\tnopl   0x0(%rax,%rax,1)\n"
~"   0x00007f5fc61850c0 <epoll_wait+130>:\t48 8b 15 41 ad 0e 00\tmov    0xead41(%rip),%rdx        # 0x7f5fc626fe08\n"
~"   0x00007f5fc61850c7 <epoll_wait+137>:\tf7 d8\tneg    %eax\n"
~"   0x00007f5fc61850c9 <epoll_wait+139>:\t64 89 02\tmov    %eax,%fs:(%rdx)\n"
~"   0x00007f5fc61850cc <epoll_wait+142>:\tb8 ff ff ff ff\tmov    $0xffffffff,%eax\n"
~"   0x00007f5fc61850d1 <epoll_wait+147>:\tc3\tret    \n"
~"   0x00007f5fc61850d2 <epoll_wait+148>:\t66 0f 1f 44 00 00\tnopw   0x0(%rax,%rax,1)\n"
~"   0x00007f5fc61850d8 <epoll_wait+154>:\t48 8b 15 29 ad 0e 00\tmov    0xead29(%rip),%rdx        # 0x7f5fc626fe08\n"
~"   0x00007f5fc61850df <epoll_wait+161>:\tf7 d8\tneg    %eax\n"
~"   0x00007f5fc61850e1 <epoll_wait+163>:\t64 89 02\tmov    %eax,%fs:(%rdx)\n"
~"   0x00007f5fc61850e4 <epoll_wait+166>:\tb8 ff ff ff ff\tmov    $0xffffffff,%eax\n"
~"   0x00007f5fc61850e9 <epoll_wait+171>:\teb bb\tjmp    0x7f5fc61850a6 <epoll_wait+104>\n"
~"   0x00007f5fc61850eb:\t0f 1f 44 00 00\tnopl   0x0(%rax,%rax,1)\n"
~"   0x00007f5fc61850f0:\t90\tnop\n"
~"   0x00007f5fc61850f1:\t90\tnop\n"
~"   0x00007f5fc61850f2:\t90\tnop\n"
~"   0x00007f5fc61850f3:\t90\tnop\n"
~"   0x00007f5fc61850f4:\t90\tnop\n"
~"   0x00007f5fc61850f5:\t90\tnop\n"
~"   0x00007f5fc61850f6:\t90\tnop\n"
~"   0x00007f5fc61850f7:\t90\tnop\n"
~"   0x00007f5fc61850f8:\t90\tnop\n"
~"   0x00007f5fc61850f9:\t90\tnop\n"
~"   0x00007f5fc61850fa:\t90\tnop\n"
~"   0x00007f5fc61850fb:\t90\tnop\n"
~"   0x00007f5fc61850fc:\t90\tnop\n"
~"   0x00007f5fc61850fd:\t90\tnop\n"
~"   0x00007f5fc61850fe <tee+0>:\tf3 0f 1e fa\tendbr64 \n"
~"   0x00007f5fc6185102 <tee+4>:\t90\tnop\n"
~"   0x00007f5fc6185103 <tee+5>:\t90\tnop\n"
~"   0x00007f5fc6185104 <tee+6>:\t41 89 ca\tmov    %ecx,%r10d\n"
~"   0x00007f5fc6185107 <tee+9>:\t64 8b 04 25 18 00 00 00\tmov    %fs:0x18,%eax\n"
~"   0x00007f5fc618510f <tee+17>:\t85 c0\ttest   %eax,%eax\n"
~"   0x00007f5fc6185111 <tee+19>:\t75 15\tjne    0x7f5fc6185128 <tee+42>\n"
~"   0x00007f5fc6185113 <tee+21>:\tb8 14 01 00 00\tmov    $0x114,%eax\n"
~"   0x00007f5fc6185118 <tee+26>:\t0f 05\tsyscall \n"
~"   0x00007f5fc618511a <tee+28>:\t48 3d 00 f0 ff ff\tcmp    $0xfffffffffffff000,%rax\n"
~"   0x00007f5fc6185120 <tee+34>:\t77 5e\tja     0x7f5fc6185180 <tee+130>\n"
~"End of assembler dump.\n"
^done
0.0012493133544921875
Last command: pince-examine-expressions
&"/dev/shm/PINCE-connection/25105/gdb_command.txt:1: Error in sourced command file:\n"
&"Undefined command: \"pince-examine-expressions\".  Try \"help\".\n"
^error,msg="/dev/shm/PINCE-connection/25105/gdb_command.txt:1: Error in sourced command file:\nUndefined command: \"pince-examine-expressions\".  Try \"help\"."
Traceback (most recent call last):
  File "/home/zephryn/download/git/PINCE/PINCE.py", line 2864, in on_process_stop
    self.disassemble_expression("$pc")
  File "/home/zephryn/download/git/PINCE/PINCE.py", line 2699, in disassemble_expression
    program_counter = GDB_Engine.examine_expression("$pc").address
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 988, in examine_expression
    return send_command("pince-examine-expressions", send_with_file=True, file_contents_send=[expression],
  File "/home/zephryn/download/git/PINCE/libpince/GDB_Engine.py", line 238, in send_command
    output = pickle.load(open(recv_file, "rb"))
EOFError: Ran out of input
```

**Comment by korcankaraokcu** [comment]
GDBCommandExtensions failed to load due to missing distorm3 package. The rest of the errors occur because of it. Try to install the package manually. Also linking this to #122

**Comment by zephryn** [comment]
Ah yep, that did the trick. Don't know how I missed that in the log lol, many thanks.
