### ISSUE TITLE
Fail to start on Chromebook 3 (Debian 11)

### ISSUE THREAD

**Issue by fantasmashy** [korcankaraokcu/PINCE#148]
it's not a surprise that something doesn't work on chromebook...
it gives this error:

```
debian@penguin:~/PINCE$ sudo sh PINCE.sh
PINCE.sh: 20: lsb_release: not found
PINCE.sh: 22: [: =: unexpected operator
Traceback (most recent call last):
  File "/home/debian/PINCE/PINCE.py", line 33, in <module>
    from libpince.libscanmem.scanmem import Scanmem
  File "/home/debian/PINCE/libpince/libscanmem/scanmem.py", line 28, in <module>
    from . import misc
  File "/home/debian/PINCE/libpince/libscanmem/misc.py", line 24, in <module>
    from gi.repository import Gtk
ModuleNotFoundError: No module named 'gi'
```

**Comment by korcankaraokcu** [comment]
Chromebook isn't currently supported, sorry about that. About your error, try installing `lsb_release` or anything that satisfies the same functionality. You might need to create an alias for it

**Comment by fantasmashy** [comment]
hm, still 
```
debian@penguin:~/PINCE$ sudo sh PINCE.sh
Traceback (most recent call last):
  File "/home/debian/PINCE/PINCE.py", line 33, in <module>
    from libpince.libscanmem.scanmem import Scanmem
  File "/home/debian/PINCE/libpince/libscanmem/scanmem.py", line 28, in <module>
    from . import misc
  File "/home/debian/PINCE/libpince/libscanmem/misc.py", line 24, in <module>
    from gi.repository import Gtk
ModuleNotFoundError: No module named 'gi'
```

**Comment by korcankaraokcu** [comment]
A quick google search recommends installing `python3-gi`, might be different for Chromebook

**Comment by fantasmashy** [comment]
just installed pygobject

```
sudo bash PINCE.sh
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
/home/debian/PINCE/libpince/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

PINCE.sh: line 27:  1727 Aborted                 sudo -E python3 PINCE.py
```

**Comment by korcankaraokcu** [comment]
Try installing `libqt5-dxcbplugin`

**Comment by korcankaraokcu** [comment]
You also might want to use `PINCE.sh` to launch pince. If you are manually invoking python3, you might get env related issues like that

**Comment by fantasmashy** [comment]
i always used sh file, i had the sudo problem too.

and i had to format linux, now it's worst:

```
debian@penguin:~/PINCE$ sudo ./PINCE.sh
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
/home/debian/PINCE/libpince/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
No protocol specified
No protocol specified
qt.qpa.xcb: could not connect to display :0
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
./PINCE.sh: line 27: 16247 Segmentation fault      sudo -E PYTHONDONTWRITEBYTECODE=1 python3 PINCE.py
```

**Comment by fantasmashy** [comment]
and... I think this is the end of my career as a romhacker

**Comment by korcankaraokcu** [comment]
`PINCE.sh` already calls sudo within, try invoking it without sudo. The effect probably will be the same but sometimes weird stuff happen, try it out

Btw, if you only want to search and modify variables within memory you can try [scanmem](https://github.com/scanmem/scanmem)

**Comment by korcankaraokcu** [comment]
Linking this to #153

**Comment by korcankaraokcu** [comment]
The latest patch fixes GTK related issues. You can try to do a clean reinstallation if you want

**Comment by korcankaraokcu** [comment]
If you ever want to reinstall PINCE, you can also try the solution in #174

**Comment by korcankaraokcu** [comment]
Installation script has been updated, try to reinstall from scratch. Do not use sudo while installing or launching the program, the scripts will handle it for you

**Comment by fantasmashy** [comment]
i'm not using the chromebook anymore but let's see...

installs a lot of things and then...

```
Selecting previously unselected package python3-yaml.
Preparing to unpack .../132-python3-yaml_5.3.1-5_amd64.deb ...
Unpacking python3-yaml (5.3.1-5) ...
Setting up python3-pkg-resources (52.0.0-4) ...
dpkg: unrecoverable fatal error, aborting:
 unable to fsync updated status of 'python3-pkg-resources': Input/output error
E: Sub-process /usr/bin/dpkg returned an error code (2)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - pkgDPkgPM::Go (30: Read-only file system)

Error occured while installing PINCE, check the output above for more information
Installation failed.
```
[the entire thing.txt](https://github.com/korcankaraokcu/PINCE/files/11379081/the.entire.thing.txt)

**Comment by brkzlr** [comment]
Your filesystem looks to be a bit corrupt since it's now stuck in a read-only state, which is usually the default behaviour for when errors are detected. You'll have to use fsck or other file system checking tools to correct any errors you might have and re-mount it as writable.

**Comment by fantasmashy** [comment]
i cannot use fsck but I think i just had to restart it...
i got installed, and here, (after install gtk3):

```
braswell@penguin:~/PINCE$ sh PINCE.sh
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/_nixkeyboard.py:110: UserWarning: Failed to create a device file using `uinput` module. Sending of events may be limited or unavailable depending on plugged-in devices.
  device = aggregate_devices('kbd')
Traceback (most recent call last):
  File "/home/braswell/PINCE/PINCE.py", line 5925, in <module>
    window = MainForm()
  File "/home/braswell/PINCE/PINCE.py", line 403, in __init__
    hotkey.change_func(func)
  File "/home/braswell/PINCE/PINCE.py", line 131, in change_func
    self.handle = add_hotkey(self.default, func)
  File "/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/_nixkeyboard.py", line 110, in build_device
    device = aggregate_devices('kbd')
  File "/home/braswell/PINCE/.venv/PINCE/lib/python3.9/site-packages/keyboard/_nixcommon.py", line 168, in aggregate_devices
    assert fake_device
AssertionError

```

**Comment by korcankaraokcu** [comment]
Keyboard module uses uinput, enable it before starting pince

**Comment by fantasmashy** [comment]
debian 11, though, i don't think is fully functional..

**Comment by fantasmashy** [comment]
chatgpt said i cannot access uinput without changing the kernel configuration and that sounds scary.
close the issue.

**Comment by korcankaraokcu** [comment]
> chatgpt said

Sometimes stackoverflow works better, try that next time. The command you want is `sudo modprobe uinput`

**Comment by korcankaraokcu** [comment]
So, did it work?

**Comment by korcankaraokcu** [comment]
Any updates on this? If not, I'll close soon as you suggested

**Comment by korcankaraokcu** [comment]
Closed due to inactivity
