### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Blu3cr0ss** [korcankaraokcu/PINCE#169]
![image](https://user-images.githubusercontent.com/49835293/218434503-f5f3903d-bffe-4ff2-bfbd-fefd4d6216c2.png)
when i trying to scroll this its giving me error: 
```
Traceback (most recent call last):
  File "/usr/share/PINCE/PINCE.py", line 2905, in disassemble_scrollbar_sliderchanged
    self.tableWidget_Disassemble_scroll("next", instructions_per_scroll)
  File "/usr/share/PINCE/PINCE.py", line 3477, in tableWidget_Disassemble_scroll
    new_address = GDB_Engine.find_closest_instruction_address(current_address, where, instruction_count)
  File "/usr/share/PINCE/libpince/GDB_Engine.py", line 1040, in find_closest_instruction_address
    disas_data = disassemble(address, address + offset)
  File "/usr/share/PINCE/libpince/GDB_Engine.py", line 951, in disassemble
    output = send_command("disas /r " + expression + "," + offset_or_address)
  File "/usr/share/PINCE/libpince/GDB_Engine.py", line 204, in send_command
    raise type_defs.InferiorRunningException
```
and not scrolling
im on archlinux

**Comment by brkzlr** [comment]
This is not a bug. You cannot scroll through the disassembly view without pausing the process first. (InferiorRunningException)
This is a GDB limitation.

Press F1 or F2 first to pause/break the process then you can scroll down. Try to use F1 (pause) to not lose your view inside the disassembly view.

**Comment by korcankaraokcu** [comment]
He's right, it's also written within the wiki, take a look:

https://github.com/korcankaraokcu/PINCE/wiki

**Comment by Blu3cr0ss** [comment]
Okay thanks
