### ISSUE TITLE
PINCE not starting Surface Pro 8 Ubuntu 22.04

### ISSUE THREAD

**Issue by LovisR** [korcankaraokcu/PINCE#206]
when i try starting Pince with 
`sh PINCE.sh`
the console returns 
```

Traceback (most recent call last):
  File "/home/lovis/PINCE/PINCE.py", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

```

**Comment by LovisR** [comment]
also i do have python3-gi installed

**Comment by brkzlr** [comment]
@korcankaraokcu I don't remember exactly why we didn't add it but I think maybe we should add `PyGObject` to pip's package list as we're explicitly importing gi?

Or maybe do a double check and see if the issues we were having with GTK are gone so we can remove this line and get rid of the gi dependency.

**Comment by LovisR** [comment]
```
/home/lovis/PINCE/.venv/PINCE/bin/python3 --version
Python 3.9.12

```

**Comment by brkzlr** [comment]
Did you have PINCE installed for some time? If yes, does this still happen if you purge the folder and re-download/re-install PINCE?
Otherwise I'm not sure why there would be different python versions between your distro package manager and pip's.

@korcankaraokcu You might be able to give it a better look as you have a VM of Ubuntu.

**Comment by LovisR** [comment]
just to be sure, do you mean to remove lines 21 and 26 of PINCE.sh?

**Comment by LovisR** [comment]
i tried removing those lines from Pince.sh, but that didnt work, and returned following error 

```
sh PINCE.sh
Traceback (most recent call last):
  File "/home/lovis/PINCE/PINCE.py", line 22, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

```
then i thought you might have ment the PINCE.py file, where i removed the lines that imported/required GI, and got the following error back
```
sh PINCE.sh
Traceback (most recent call last):
  File "/home/lovis/PINCE/PINCE.py", line 28, in <module>
    from PyQt6.QtGui import QIcon, QMovie, QPixmap, QCursor, QKeySequence, QColor, QTextCharFormat, QBrush, QTextCursor, \
ModuleNotFoundError: No module named 'PyQt6'
```

**Comment by korcankaraokcu** [comment]
> then i thought you might have ment the PINCE.py file

Yeah, mb. I meant the py file. I've read that too fast

> ModuleNotFoundError: No module named 'PyQt6'

That's impossible. You've literally installed it:
`Requirement already satisfied: pyqt6 in ./.venv/PINCE/lib/python3.9/site-packages (6.5.2)`

Maybe @brkzlr is right on the issue
> From your logs I'm seeing that Python 3 should be 3.10 but pip's packages are on 3.9 so it might be a version mismatch.

Try to use the same version with pip while launching PINCE

**Comment by brkzlr** [comment]
If those are installed and it won't work then my guess is that venv fails to activate @korcankaraokcu 

Basically line 28 or 33 of `PINCE.sh`.

Either user's shell doesn't support the way we activate it or the `preserve-env` flag used to fix Ubuntu/Debian failed.

**Comment by vitalNohj** [comment]
> when i try starting Pince with `sh PINCE.sh` the console returns
> 
> ```
> 
> Traceback (most recent call last):
>   File "/home/lovis/PINCE/PINCE.py", line 21, in <module>
>     import gi
> ModuleNotFoundError: No module named 'gi'
> ```

I have the same issue with a Surface Book on Ubuntu 22.04.
Are you running the surface kernel patch too?

**Comment by PauloAxcel** [comment]
I had the same error as you. What appears to be the issue is that you have multiple python versions installed at the same time. In my case, I add anaconda3 and then another python version in the usr/bin. What I did was to delete the anaconda3 directory, delete PINCE and install again PINCE. After that, everything ran fine!

 I just followed these instructions on how to uninstall anaconda

https://stackoverflow.com/questions/22585235/python-anaconda-how-to-safely-uninstall

and this one to find how many python versions do I have installed

https://askubuntu.com/questions/1257144/python-package-gi-is-not-found-although-python3-gi-is-installed

Might not be the same issues though, but for me, it worked, and I had exactly the same error message as you!
Hope it helps!

**Comment by brkzlr** [comment]
@LovisR @vitalNohj @PauloAxcel Can you try the newest AppImage, tagged v0.2? Read the new installation & running instructions and it should work without doing any setup.

**Comment by brkzlr** [comment]
Closing due to inactivity. If it happens again in the future, feel free to comment again.
