### ISSUE TITLE
TypeError when attaching to process

### ISSUE THREAD

**Issue by dejj** [korcankaraokcu/PINCE#23]
Clicking the "attach to process"-button causes the following error:

```
Traceback (most recent call last):
  File "PINCE.py", line 475, in pushButton_AttachProcess_clicked
    self.processwindow = ProcessForm(self)
  File "PINCE.py", line 605, in __init__
    self.refresh_process_table(self.tableWidget_ProcessTable, processlist)
  File "PINCE.py", line 629, in refresh_process_table
    tablewidget.setItem(i, 1, QTableWidgetItem(row.username()))
TypeError: 'str' object is not callable
```

**Comment by korcankaraokcu** [comment]
I had the same error at the beginning of the project. It happens because of the different psutil versions. This [commit](https://github.com/korcankaraokcu/PINCE/commit/7fc9cc1af6c6fc4e6d3d7f874596a9558392059d) should fix the issue. Please do a `git pull` and report me back.

Btw, github automatically closed the issue at the moment I committed the patch, sorry for that. Re-opening now

**Comment by korcankaraokcu** [comment]
Did tests on multiple psutil versions, it works. Please re-open this issue if you encounter problems.
