### ISSUE TITLE
pct files not opened properly & a bunch of quality of usage requests

### ISSUE THREAD

**Issue by awsdert** [korcankaraokcu/PINCE#96]
```
Last command: pince-examine-expressions
&"/dev/shm/PINCE-connection/-1/gdb_command.txt:1: Error in sourced command file:\n"
&"Undefined command: \"pince-examine-expressions\".  Try \"help\".\n"
^error,msg="/dev/shm/PINCE-connection/-1/gdb_command.txt:1: Error in sourced command file:\nUndefined command: \"pince-examine-expressions\".  Try \"help\"."
Traceback (most recent call last):
  File "/usr/share/PINCE/PINCE.py", line 604, in treeWidget_AddressTable_context_menu_event
    actions[action]()
  File "/usr/share/PINCE/PINCE.py", line 597, in <lambda>
    paste_record_inside: lambda: self.paste_records(insert_inside=True),
  File "/usr/share/PINCE/PINCE.py", line 716, in paste_records
    self.insert_records(records, root, self.treeWidget_AddressTable.topLevelItemCount())
  File "/usr/share/PINCE/PINCE.py", line 700, in insert_records
    self.change_address_table_entries(row, *rec[:-1])
  File "/usr/share/PINCE/PINCE.py", line 1135, in change_address_table_entries
    address = GDB_Engine.examine_expression(address_expr).address
  File "/usr/share/PINCE/libPINCE/GDB_Engine.py", line 993, in examine_expression
    return send_command("pince-examine-expressions", send_with_file=True, file_contents_send=[expression],
  File "/usr/share/PINCE/libPINCE/GDB_Engine.py", line 238, in send_command
    output = pickle.load(open(recv_file, "rb"))
EOFError: Ran out of input
```
Is what I get when I try to open a file saved by pince, I saved it to a different directory, the dialog sees the files just fine but 
nothing here.

Now for the requests:
- Option to change default path for saving/loading files to/from
- Option to limit the address range searched in, gets annoying to search an entire process when I only wanted to search say 0x4'0000'0000-0x5'0000'0000 (would appreciate separator support but not a big priority)
- A "recalculate addresses" feature like Cheat Engine has, gets real annoying to have to manually redo each address
- Sort records by address &/or name
- Ability to read memory without the STOP_PROCESS/CONT_PROCESS crap, just add a warning that it's gonna be a snapshot of the memory and then add a button to get a new snapshot, highlighting cells different to previous snapshot would be welcome too.
- The ability to use Page Up/Down to do large jumps of memory at a time (just make the jump the same as what can be displayed), scrollwheel just hurts my finger after a while

**Comment by awsdert** [comment]
I'm finding the current work around is to add a random address manually, copy the contents of the file and paste around the record, without the record it just blatantly refuses to add anything so I think the main fault lies in the code that adds the records assuming that a record or records exist already and trying to hook them instead, look around that area whereever that may be.

**Comment by awsdert** [comment]
```
Traceback (most recent call last):
  File "/usr/share/PINCE/PINCE.py", line 984, in pushButton_Open_clicked
    self.insert_records(content, self.treeWidget_AddressTable.invisibleRootItem(),
  File "/usr/share/PINCE/PINCE.py", line 721, in insert_records
    self.change_address_table_entries(row, *rec[:-1])
TypeError: change_address_table_entries() takes from 2 to 5 positional arguments but 64 were given
```
[DQB_EU.pct.txt](https://github.com/korcankaraokcu/PINCE/files/6247918/DQB_EU.pct.txt)

**Comment by awsdert** [comment]
Just noticed your messages, as far as the user permissions go there's a workaround for that, first pince should be a subprocess launched with pkexec or something internally, this will give it the permissions it needs, the main process can examine /root/.pince/[user] or whatever directory it told pince to store the tables in, then when pince exits it just needs to copy them over, when pince is booted the main process can just tell where the selected directory is, yes the shutdown will be slightly slower because of the copying but it is unlikely to be enough to be noticeable in most cases.

For scanning by absolute address I'm sure scanmem has something for blobs or files, just copy from /proc/<pid>/mem to a file the range that's been set then scan, this will actually make it less likely that a process will notice pince at kill it too.

As for the other fair enough.

**Comment by awsdert** [comment]
> Pkexec is a proper fix for read-only data, I agree. But for the scripts, it's going to be the same. If a script is getting executed by a root priv process, the same script shouldn't be accessed by non-priv users. A solution for this case would be to separate cheat tables entirely from user_files structure. But again, cheat tables will integrate scripts for convenience in the future. So, this change only can be temporary. This is why I don't want to implement it, it's going to be removed eventually. If you are thinking about gdb launching a non-priv subprocess, that would be useless because a debugee can be only debugged by one process
> 
> Scanmem only has region selection, not absolute addresses. As for copying, it's easy for kernel modules to detect when that file is opened, regardless of how many bytes you've copied
> 
> I cannot seem to find any files in the root folder

First why would the scripts matter? If they can't do anything without root permissions then it won't matter if a user attempt to run them, they'll just fail, not like they should be run outside of pince anyhow, anyways what kinda scripts would even be executable outside of pince where they would have the permissions they need?

Second it doesn't matter that kernel modules can detect /proc/<pid>/mem being opened, I've never had one shut down my own app when accessing it, that includes the ones that detect and shutdown pince, I suspect the reason for this is because I'm never attached long enough for them to grab the process id which means my method of copy the memory I need first and quickly detach is the correct method of scanning process memory on linux as it severely reduces the likely hood  the target process can catch the scanners pid, it also means it doesn't take long for the game to return to being playable since once you got the snapshot of the memory you don't need to be attached, instead you can just scan the snapshot which also reduces the APIs you have to deal with while scanning so you can just customise a scanner to deal with just memory blobs, copy process memory to a set of files representing each mapped memory space and then just read those into a blob and pass it to the scanner, one blob to deal with, small enough remain directly in pince's memory and easy to deal with, only attach gdb long term if you need to pause the game.

As for files in the root folder I pulled that one out of memory, been a while since I used pince due to issues getting games to run at all, ended up re-installing my system which seemed to solve that issue, when I a get to a point in my DQB2 where I want to hack a value or 2 again then I'll try pince again then.
